---
#
# Carvel tools (including ytt) https://github.com/carvel-dev/ytt
#
-
- name: Download Carvel installation script
  ansible.builtin.get_url:
    url: https://carvel.dev/install.sh
    dest: /tmp/install.sh
    mode: '0755'  # Make the script executable

- name: Inspect the installation script (optional)
  ansible.builtin.command: cat /tmp/install.sh
  register: script_content
  changed_when: false  # This task doesn't change the system state

- name: Run the Carvel installation script
  ansible.builtin.command: bash /tmp/install.sh
  args:
    creates: /usr/local/bin/ytt  # Skip if ytt is already installed

- name: Verify ytt installation
  ansible.builtin.command: ytt version
  register: ytt_version
  changed_when: false  # This task doesn't change the system state

- name: Display ytt version
  ansible.builtin.debug:
    var: ytt_version.stdout

#
# wezterm https://wezfurlong.org/wezterm/install/linux.html
#

- name: Create apt keyrings directory if it doesn't exist
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download WezTerm GPG key
  shell: "curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg"
  args:
    creates: /etc/apt/keyrings/wezterm-fury.gpg
  become: true

- name: Add WezTerm apt repository
  shell: "echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list"
  args:
    creates: /etc/apt/sources.list.d/wezterm.list
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install WezTerm
  apt:
    name: wezterm
    state: present
  become: true