---
- name: Check if SDKMAN is installed
  stat:
    path: "{{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh"
  register: sdkman_installed

- name: Install SDKMAN
  shell: "curl -s \"https://get.sdkman.io\" | bash"
  when: not sdkman_installed.stat.exists

- name: Install Java with SDKMAN
  shell: "source {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install java {{ sdkman_java_version }}"
  args:
    executable: /bin/bash
  when: not sdkman_installed.stat.exists