---
- name: Ensure Flatpak is installed
  apt:
    name: flatpak
    state: present

- name: Add flatpak remotes
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.url }}"
    method: user
  loop: "{{ flatpak_remotes }}"

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_packages }}"