---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600  # Cache for 1 hour

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: true

- name: Install essential packages
  apt:
    name: "{{ essential_packages }}"
    state: present
    update_cache: yes